### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SergeevSergey99** [SergeevSergey99/ProfTest#3]
- [x]  invisible numbers
- [x] zero events
- [x] equal curdate events
- [x] add preload of img
- [x] vertical center in menu

- [x]  modular styles

**Comment by SergeevSergey99** [comment]
- [x] parser

- [ ] Event questions
